/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChangePasswordRequest,
  CompleteTaskRequest,
  CreateCategoryRequest,
  CreateDepartmentRequest,
  CreateDocSourceRequest,
  CreateDocumentRequest,
  CreateTaskLogRequest,
  CreateTaskRequest,
  ExportTasksParams,
  GetCategoriesParams,
  GetDepartmentsParams,
  GetDocumentsParams,
  GetTasksParams,
  LoginRequest,
  Result,
  UpdateCategoryRequest,
  UpdateDepartmentRequest,
  UpdateDocSourceRequest,
  UpdateDocumentRequest,
  UpdateTaskRequest
} from './model';

import { apiOrvalClient } from './client';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const loginUser = (
    loginRequest: LoginRequest,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest, signal
    },
      options);
    }
  


export const getLoginUserMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
): UseMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['loginUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginUser>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  loginUser(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LoginUserMutationResult = NonNullable<Awaited<ReturnType<typeof loginUser>>>
    export type LoginUserMutationBody = LoginRequest
    export type LoginUserMutationError = unknown

    export const useLoginUser = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginUser>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {
      return useMutation(getLoginUserMutationOptions(options), queryClient);
    }
    
export const refreshUser = (
    
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/auth/refresh-token`, method: 'POST', signal
    },
      options);
    }
  


export const getRefreshUserMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshUser>>, TError,void, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
): UseMutationOptions<Awaited<ReturnType<typeof refreshUser>>, TError,void, TContext> => {

const mutationKey = ['refreshUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof refreshUser>>, void> = () => {
          

          return  refreshUser(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RefreshUserMutationResult = NonNullable<Awaited<ReturnType<typeof refreshUser>>>
    
    export type RefreshUserMutationError = unknown

    export const useRefreshUser = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshUser>>, TError,void, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof refreshUser>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getRefreshUserMutationOptions(options), queryClient);
    }
    
export const logoutUser = (
    
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/auth/logout`, method: 'POST', signal
    },
      options);
    }
  


export const getLogoutUserMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logoutUser>>, TError,void, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
): UseMutationOptions<Awaited<ReturnType<typeof logoutUser>>, TError,void, TContext> => {

const mutationKey = ['logoutUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logoutUser>>, void> = () => {
          

          return  logoutUser(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LogoutUserMutationResult = NonNullable<Awaited<ReturnType<typeof logoutUser>>>
    
    export type LogoutUserMutationError = unknown

    export const useLogoutUser = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logoutUser>>, TError,void, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logoutUser>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getLogoutUserMutationOptions(options), queryClient);
    }
    
export const authChangePassword = (
    changePasswordRequest: ChangePasswordRequest,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/auth/change-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: changePasswordRequest, signal
    },
      options);
    }
  


export const getAuthChangePasswordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authChangePassword>>, TError,{data: ChangePasswordRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
): UseMutationOptions<Awaited<ReturnType<typeof authChangePassword>>, TError,{data: ChangePasswordRequest}, TContext> => {

const mutationKey = ['authChangePassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authChangePassword>>, {data: ChangePasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  authChangePassword(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AuthChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof authChangePassword>>>
    export type AuthChangePasswordMutationBody = ChangePasswordRequest
    export type AuthChangePasswordMutationError = unknown

    export const useAuthChangePassword = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authChangePassword>>, TError,{data: ChangePasswordRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authChangePassword>>,
        TError,
        {data: ChangePasswordRequest},
        TContext
      > => {
      return useMutation(getAuthChangePasswordMutationOptions(options), queryClient);
    }
    
export const getDocuments = (
    params?: GetDocumentsParams,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/documents`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetDocumentsQueryKey = (params?: GetDocumentsParams,) => {
    return [
    `/api/documents`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetDocumentsQueryOptions = <TData = Awaited<ReturnType<typeof getDocuments>>, TError = unknown>(params?: GetDocumentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocuments>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDocumentsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocuments>>> = ({ signal }) => getDocuments(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDocuments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocumentsQueryResult = NonNullable<Awaited<ReturnType<typeof getDocuments>>>
export type GetDocumentsQueryError = unknown


export function useGetDocuments<TData = Awaited<ReturnType<typeof getDocuments>>, TError = unknown>(
 params: undefined |  GetDocumentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocuments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocuments>>,
          TError,
          Awaited<ReturnType<typeof getDocuments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocuments<TData = Awaited<ReturnType<typeof getDocuments>>, TError = unknown>(
 params?: GetDocumentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocuments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocuments>>,
          TError,
          Awaited<ReturnType<typeof getDocuments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocuments<TData = Awaited<ReturnType<typeof getDocuments>>, TError = unknown>(
 params?: GetDocumentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocuments>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetDocuments<TData = Awaited<ReturnType<typeof getDocuments>>, TError = unknown>(
 params?: GetDocumentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocuments>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDocumentsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export const createDocument = (
    createDocumentRequest: CreateDocumentRequest,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/documents`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createDocumentRequest, signal
    },
      options);
    }
  


export const getCreateDocumentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDocument>>, TError,{data: CreateDocumentRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
): UseMutationOptions<Awaited<ReturnType<typeof createDocument>>, TError,{data: CreateDocumentRequest}, TContext> => {

const mutationKey = ['createDocument'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDocument>>, {data: CreateDocumentRequest}> = (props) => {
          const {data} = props ?? {};

          return  createDocument(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateDocumentMutationResult = NonNullable<Awaited<ReturnType<typeof createDocument>>>
    export type CreateDocumentMutationBody = CreateDocumentRequest
    export type CreateDocumentMutationError = unknown

    export const useCreateDocument = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDocument>>, TError,{data: CreateDocumentRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createDocument>>,
        TError,
        {data: CreateDocumentRequest},
        TContext
      > => {
      return useMutation(getCreateDocumentMutationOptions(options), queryClient);
    }
    
export const getDocumentById = (
    id: string,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/documents/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetDocumentByIdQueryKey = (id: string,) => {
    return [
    `/api/documents/${id}`
    ] as const;
    }

    
export const getGetDocumentByIdQueryOptions = <TData = Awaited<ReturnType<typeof getDocumentById>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentById>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDocumentByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocumentById>>> = ({ signal }) => getDocumentById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDocumentById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocumentByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getDocumentById>>>
export type GetDocumentByIdQueryError = unknown


export function useGetDocumentById<TData = Awaited<ReturnType<typeof getDocumentById>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentById>>,
          TError,
          Awaited<ReturnType<typeof getDocumentById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentById<TData = Awaited<ReturnType<typeof getDocumentById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentById>>,
          TError,
          Awaited<ReturnType<typeof getDocumentById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentById<TData = Awaited<ReturnType<typeof getDocumentById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentById>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetDocumentById<TData = Awaited<ReturnType<typeof getDocumentById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentById>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDocumentByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export const updateDocument = (
    id: string,
    updateDocumentRequest: UpdateDocumentRequest,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/documents/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateDocumentRequest, signal
    },
      options);
    }
  


export const getUpdateDocumentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDocument>>, TError,{id: string;data: UpdateDocumentRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
): UseMutationOptions<Awaited<ReturnType<typeof updateDocument>>, TError,{id: string;data: UpdateDocumentRequest}, TContext> => {

const mutationKey = ['updateDocument'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateDocument>>, {id: string;data: UpdateDocumentRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateDocument(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateDocumentMutationResult = NonNullable<Awaited<ReturnType<typeof updateDocument>>>
    export type UpdateDocumentMutationBody = UpdateDocumentRequest
    export type UpdateDocumentMutationError = unknown

    export const useUpdateDocument = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDocument>>, TError,{id: string;data: UpdateDocumentRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateDocument>>,
        TError,
        {id: string;data: UpdateDocumentRequest},
        TContext
      > => {
      return useMutation(getUpdateDocumentMutationOptions(options), queryClient);
    }
    
export const deleteDocument = (
    id: string,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/documents/${id}`, method: 'DELETE', signal
    },
      options);
    }
  


export const getDeleteDocumentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDocument>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDocument>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteDocument'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDocument>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteDocument(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteDocumentMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDocument>>>
    
    export type DeleteDocumentMutationError = unknown

    export const useDeleteDocument = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDocument>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDocument>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteDocumentMutationOptions(options), queryClient);
    }
    
export const getTasks = (
    params?: GetTasksParams,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/tasks`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetTasksQueryKey = (params?: GetTasksParams,) => {
    return [
    `/api/tasks`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetTasksQueryOptions = <TData = Awaited<ReturnType<typeof getTasks>>, TError = unknown>(params?: GetTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTasksQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTasks>>> = ({ signal }) => getTasks(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTasksQueryResult = NonNullable<Awaited<ReturnType<typeof getTasks>>>
export type GetTasksQueryError = unknown


export function useGetTasks<TData = Awaited<ReturnType<typeof getTasks>>, TError = unknown>(
 params: undefined |  GetTasksParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTasks>>,
          TError,
          Awaited<ReturnType<typeof getTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTasks<TData = Awaited<ReturnType<typeof getTasks>>, TError = unknown>(
 params?: GetTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTasks>>,
          TError,
          Awaited<ReturnType<typeof getTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTasks<TData = Awaited<ReturnType<typeof getTasks>>, TError = unknown>(
 params?: GetTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTasks<TData = Awaited<ReturnType<typeof getTasks>>, TError = unknown>(
 params?: GetTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTasksQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export const createTask = (
    createTaskRequest: CreateTaskRequest,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/tasks`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTaskRequest, signal
    },
      options);
    }
  


export const getCreateTaskMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTask>>, TError,{data: CreateTaskRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
): UseMutationOptions<Awaited<ReturnType<typeof createTask>>, TError,{data: CreateTaskRequest}, TContext> => {

const mutationKey = ['createTask'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTask>>, {data: CreateTaskRequest}> = (props) => {
          const {data} = props ?? {};

          return  createTask(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTaskMutationResult = NonNullable<Awaited<ReturnType<typeof createTask>>>
    export type CreateTaskMutationBody = CreateTaskRequest
    export type CreateTaskMutationError = unknown

    export const useCreateTask = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTask>>, TError,{data: CreateTaskRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTask>>,
        TError,
        {data: CreateTaskRequest},
        TContext
      > => {
      return useMutation(getCreateTaskMutationOptions(options), queryClient);
    }
    
export const getTaskById = (
    id: string,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/tasks/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetTaskByIdQueryKey = (id: string,) => {
    return [
    `/api/tasks/${id}`
    ] as const;
    }

    
export const getGetTaskByIdQueryOptions = <TData = Awaited<ReturnType<typeof getTaskById>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskById>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTaskByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTaskById>>> = ({ signal }) => getTaskById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTaskById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTaskByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getTaskById>>>
export type GetTaskByIdQueryError = unknown


export function useGetTaskById<TData = Awaited<ReturnType<typeof getTaskById>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskById>>,
          TError,
          Awaited<ReturnType<typeof getTaskById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTaskById<TData = Awaited<ReturnType<typeof getTaskById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskById>>,
          TError,
          Awaited<ReturnType<typeof getTaskById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTaskById<TData = Awaited<ReturnType<typeof getTaskById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskById>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTaskById<TData = Awaited<ReturnType<typeof getTaskById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskById>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTaskByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export const updateTask = (
    id: string,
    updateTaskRequest: UpdateTaskRequest,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/tasks/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateTaskRequest, signal
    },
      options);
    }
  


export const getUpdateTaskMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTask>>, TError,{id: string;data: UpdateTaskRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
): UseMutationOptions<Awaited<ReturnType<typeof updateTask>>, TError,{id: string;data: UpdateTaskRequest}, TContext> => {

const mutationKey = ['updateTask'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTask>>, {id: string;data: UpdateTaskRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateTask(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateTaskMutationResult = NonNullable<Awaited<ReturnType<typeof updateTask>>>
    export type UpdateTaskMutationBody = UpdateTaskRequest
    export type UpdateTaskMutationError = unknown

    export const useUpdateTask = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTask>>, TError,{id: string;data: UpdateTaskRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTask>>,
        TError,
        {id: string;data: UpdateTaskRequest},
        TContext
      > => {
      return useMutation(getUpdateTaskMutationOptions(options), queryClient);
    }
    
export const deleteTask = (
    id: string,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/tasks/${id}`, method: 'DELETE', signal
    },
      options);
    }
  


export const getDeleteTaskMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTask>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteTask>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteTask'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTask>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteTask(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteTaskMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTask>>>
    
    export type DeleteTaskMutationError = unknown

    export const useDeleteTask = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTask>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTask>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteTaskMutationOptions(options), queryClient);
    }
    
export const completeTaskById = (
    id: string,
    completeTaskRequest: CompleteTaskRequest,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/tasks/${id}/complete`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: completeTaskRequest, signal
    },
      options);
    }
  


export const getCompleteTaskByIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeTaskById>>, TError,{id: string;data: CompleteTaskRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
): UseMutationOptions<Awaited<ReturnType<typeof completeTaskById>>, TError,{id: string;data: CompleteTaskRequest}, TContext> => {

const mutationKey = ['completeTaskById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeTaskById>>, {id: string;data: CompleteTaskRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  completeTaskById(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CompleteTaskByIdMutationResult = NonNullable<Awaited<ReturnType<typeof completeTaskById>>>
    export type CompleteTaskByIdMutationBody = CompleteTaskRequest
    export type CompleteTaskByIdMutationError = unknown

    export const useCompleteTaskById = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeTaskById>>, TError,{id: string;data: CompleteTaskRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completeTaskById>>,
        TError,
        {id: string;data: CompleteTaskRequest},
        TContext
      > => {
      return useMutation(getCompleteTaskByIdMutationOptions(options), queryClient);
    }
    
export const exportTasks = (
    params?: ExportTasksParams,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/tasks/export`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getExportTasksQueryKey = (params?: ExportTasksParams,) => {
    return [
    `/api/tasks/export`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getExportTasksQueryOptions = <TData = Awaited<ReturnType<typeof exportTasks>>, TError = unknown>(params?: ExportTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportTasks>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExportTasksQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof exportTasks>>> = ({ signal }) => exportTasks(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof exportTasks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExportTasksQueryResult = NonNullable<Awaited<ReturnType<typeof exportTasks>>>
export type ExportTasksQueryError = unknown


export function useExportTasks<TData = Awaited<ReturnType<typeof exportTasks>>, TError = unknown>(
 params: undefined |  ExportTasksParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportTasks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportTasks>>,
          TError,
          Awaited<ReturnType<typeof exportTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportTasks<TData = Awaited<ReturnType<typeof exportTasks>>, TError = unknown>(
 params?: ExportTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportTasks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportTasks>>,
          TError,
          Awaited<ReturnType<typeof exportTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportTasks<TData = Awaited<ReturnType<typeof exportTasks>>, TError = unknown>(
 params?: ExportTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportTasks>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useExportTasks<TData = Awaited<ReturnType<typeof exportTasks>>, TError = unknown>(
 params?: ExportTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportTasks>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExportTasksQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export const getTaskLogs = (
    taskId: string,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/tasks/${taskId}/logs`, method: 'GET', signal
    },
      options);
    }
  



export const getGetTaskLogsQueryKey = (taskId: string,) => {
    return [
    `/api/tasks/${taskId}/logs`
    ] as const;
    }

    
export const getGetTaskLogsQueryOptions = <TData = Awaited<ReturnType<typeof getTaskLogs>>, TError = unknown>(taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskLogs>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTaskLogsQueryKey(taskId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTaskLogs>>> = ({ signal }) => getTaskLogs(taskId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(taskId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTaskLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTaskLogsQueryResult = NonNullable<Awaited<ReturnType<typeof getTaskLogs>>>
export type GetTaskLogsQueryError = unknown


export function useGetTaskLogs<TData = Awaited<ReturnType<typeof getTaskLogs>>, TError = unknown>(
 taskId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskLogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskLogs>>,
          TError,
          Awaited<ReturnType<typeof getTaskLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTaskLogs<TData = Awaited<ReturnType<typeof getTaskLogs>>, TError = unknown>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskLogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskLogs>>,
          TError,
          Awaited<ReturnType<typeof getTaskLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTaskLogs<TData = Awaited<ReturnType<typeof getTaskLogs>>, TError = unknown>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskLogs>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTaskLogs<TData = Awaited<ReturnType<typeof getTaskLogs>>, TError = unknown>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskLogs>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTaskLogsQueryOptions(taskId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export const createTaskLog = (
    taskId: string,
    createTaskLogRequest: CreateTaskLogRequest,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/tasks/${taskId}/logs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTaskLogRequest, signal
    },
      options);
    }
  


export const getCreateTaskLogMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTaskLog>>, TError,{taskId: string;data: CreateTaskLogRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
): UseMutationOptions<Awaited<ReturnType<typeof createTaskLog>>, TError,{taskId: string;data: CreateTaskLogRequest}, TContext> => {

const mutationKey = ['createTaskLog'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTaskLog>>, {taskId: string;data: CreateTaskLogRequest}> = (props) => {
          const {taskId,data} = props ?? {};

          return  createTaskLog(taskId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTaskLogMutationResult = NonNullable<Awaited<ReturnType<typeof createTaskLog>>>
    export type CreateTaskLogMutationBody = CreateTaskLogRequest
    export type CreateTaskLogMutationError = unknown

    export const useCreateTaskLog = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTaskLog>>, TError,{taskId: string;data: CreateTaskLogRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTaskLog>>,
        TError,
        {taskId: string;data: CreateTaskLogRequest},
        TContext
      > => {
      return useMutation(getCreateTaskLogMutationOptions(options), queryClient);
    }
    
export const getDashboard = (
    
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/dashboard`, method: 'GET', signal
    },
      options);
    }
  



export const getGetDashboardQueryKey = () => {
    return [
    `/api/dashboard`
    ] as const;
    }

    
export const getGetDashboardQueryOptions = <TData = Awaited<ReturnType<typeof getDashboard>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboard>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboard>>> = ({ signal }) => getDashboard(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDashboard>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDashboardQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboard>>>
export type GetDashboardQueryError = unknown


export function useGetDashboard<TData = Awaited<ReturnType<typeof getDashboard>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboard>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboard>>,
          TError,
          Awaited<ReturnType<typeof getDashboard>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboard<TData = Awaited<ReturnType<typeof getDashboard>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboard>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboard>>,
          TError,
          Awaited<ReturnType<typeof getDashboard>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboard<TData = Awaited<ReturnType<typeof getDashboard>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboard>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetDashboard<TData = Awaited<ReturnType<typeof getDashboard>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboard>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDashboardQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export const getDocSources = (
    
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/doc-sources`, method: 'GET', signal
    },
      options);
    }
  



export const getGetDocSourcesQueryKey = () => {
    return [
    `/api/doc-sources`
    ] as const;
    }

    
export const getGetDocSourcesQueryOptions = <TData = Awaited<ReturnType<typeof getDocSources>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocSources>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDocSourcesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocSources>>> = ({ signal }) => getDocSources(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDocSources>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocSourcesQueryResult = NonNullable<Awaited<ReturnType<typeof getDocSources>>>
export type GetDocSourcesQueryError = unknown


export function useGetDocSources<TData = Awaited<ReturnType<typeof getDocSources>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocSources>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocSources>>,
          TError,
          Awaited<ReturnType<typeof getDocSources>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocSources<TData = Awaited<ReturnType<typeof getDocSources>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocSources>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocSources>>,
          TError,
          Awaited<ReturnType<typeof getDocSources>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocSources<TData = Awaited<ReturnType<typeof getDocSources>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocSources>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetDocSources<TData = Awaited<ReturnType<typeof getDocSources>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocSources>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDocSourcesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export const createDocSource = (
    createDocSourceRequest: CreateDocSourceRequest,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/doc-sources`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createDocSourceRequest, signal
    },
      options);
    }
  


export const getCreateDocSourceMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDocSource>>, TError,{data: CreateDocSourceRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
): UseMutationOptions<Awaited<ReturnType<typeof createDocSource>>, TError,{data: CreateDocSourceRequest}, TContext> => {

const mutationKey = ['createDocSource'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDocSource>>, {data: CreateDocSourceRequest}> = (props) => {
          const {data} = props ?? {};

          return  createDocSource(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateDocSourceMutationResult = NonNullable<Awaited<ReturnType<typeof createDocSource>>>
    export type CreateDocSourceMutationBody = CreateDocSourceRequest
    export type CreateDocSourceMutationError = unknown

    export const useCreateDocSource = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDocSource>>, TError,{data: CreateDocSourceRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createDocSource>>,
        TError,
        {data: CreateDocSourceRequest},
        TContext
      > => {
      return useMutation(getCreateDocSourceMutationOptions(options), queryClient);
    }
    
export const getDocSourceById = (
    id: number,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/doc-sources/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetDocSourceByIdQueryKey = (id: number,) => {
    return [
    `/api/doc-sources/${id}`
    ] as const;
    }

    
export const getGetDocSourceByIdQueryOptions = <TData = Awaited<ReturnType<typeof getDocSourceById>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocSourceById>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDocSourceByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocSourceById>>> = ({ signal }) => getDocSourceById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDocSourceById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocSourceByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getDocSourceById>>>
export type GetDocSourceByIdQueryError = unknown


export function useGetDocSourceById<TData = Awaited<ReturnType<typeof getDocSourceById>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocSourceById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocSourceById>>,
          TError,
          Awaited<ReturnType<typeof getDocSourceById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocSourceById<TData = Awaited<ReturnType<typeof getDocSourceById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocSourceById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocSourceById>>,
          TError,
          Awaited<ReturnType<typeof getDocSourceById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocSourceById<TData = Awaited<ReturnType<typeof getDocSourceById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocSourceById>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetDocSourceById<TData = Awaited<ReturnType<typeof getDocSourceById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocSourceById>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDocSourceByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export const updateDocSource = (
    id: number,
    updateDocSourceRequest: UpdateDocSourceRequest,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/doc-sources/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateDocSourceRequest, signal
    },
      options);
    }
  


export const getUpdateDocSourceMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDocSource>>, TError,{id: number;data: UpdateDocSourceRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
): UseMutationOptions<Awaited<ReturnType<typeof updateDocSource>>, TError,{id: number;data: UpdateDocSourceRequest}, TContext> => {

const mutationKey = ['updateDocSource'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateDocSource>>, {id: number;data: UpdateDocSourceRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateDocSource(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateDocSourceMutationResult = NonNullable<Awaited<ReturnType<typeof updateDocSource>>>
    export type UpdateDocSourceMutationBody = UpdateDocSourceRequest
    export type UpdateDocSourceMutationError = unknown

    export const useUpdateDocSource = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDocSource>>, TError,{id: number;data: UpdateDocSourceRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateDocSource>>,
        TError,
        {id: number;data: UpdateDocSourceRequest},
        TContext
      > => {
      return useMutation(getUpdateDocSourceMutationOptions(options), queryClient);
    }
    
export const deleteDocSource = (
    id: number,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/doc-sources/${id}`, method: 'DELETE', signal
    },
      options);
    }
  


export const getDeleteDocSourceMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDocSource>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDocSource>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteDocSource'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDocSource>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteDocSource(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteDocSourceMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDocSource>>>
    
    export type DeleteDocSourceMutationError = unknown

    export const useDeleteDocSource = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDocSource>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDocSource>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteDocSourceMutationOptions(options), queryClient);
    }
    
export const getCategories = (
    params?: GetCategoriesParams,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/categories`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetCategoriesQueryKey = (params?: GetCategoriesParams,) => {
    return [
    `/api/categories`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetCategoriesQueryOptions = <TData = Awaited<ReturnType<typeof getCategories>>, TError = unknown>(params?: GetCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCategoriesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCategories>>> = ({ signal }) => getCategories(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof getCategories>>>
export type GetCategoriesQueryError = unknown


export function useGetCategories<TData = Awaited<ReturnType<typeof getCategories>>, TError = unknown>(
 params: undefined |  GetCategoriesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCategories>>,
          TError,
          Awaited<ReturnType<typeof getCategories>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCategories<TData = Awaited<ReturnType<typeof getCategories>>, TError = unknown>(
 params?: GetCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCategories>>,
          TError,
          Awaited<ReturnType<typeof getCategories>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCategories<TData = Awaited<ReturnType<typeof getCategories>>, TError = unknown>(
 params?: GetCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCategories<TData = Awaited<ReturnType<typeof getCategories>>, TError = unknown>(
 params?: GetCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCategoriesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export const createCategory = (
    createCategoryRequest: CreateCategoryRequest,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/categories`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCategoryRequest, signal
    },
      options);
    }
  


export const getCreateCategoryMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCategory>>, TError,{data: CreateCategoryRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
): UseMutationOptions<Awaited<ReturnType<typeof createCategory>>, TError,{data: CreateCategoryRequest}, TContext> => {

const mutationKey = ['createCategory'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCategory>>, {data: CreateCategoryRequest}> = (props) => {
          const {data} = props ?? {};

          return  createCategory(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof createCategory>>>
    export type CreateCategoryMutationBody = CreateCategoryRequest
    export type CreateCategoryMutationError = unknown

    export const useCreateCategory = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCategory>>, TError,{data: CreateCategoryRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCategory>>,
        TError,
        {data: CreateCategoryRequest},
        TContext
      > => {
      return useMutation(getCreateCategoryMutationOptions(options), queryClient);
    }
    
export const getCategoryById = (
    id: number,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/categories/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetCategoryByIdQueryKey = (id: number,) => {
    return [
    `/api/categories/${id}`
    ] as const;
    }

    
export const getGetCategoryByIdQueryOptions = <TData = Awaited<ReturnType<typeof getCategoryById>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategoryById>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCategoryByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCategoryById>>> = ({ signal }) => getCategoryById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCategoryById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCategoryByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getCategoryById>>>
export type GetCategoryByIdQueryError = unknown


export function useGetCategoryById<TData = Awaited<ReturnType<typeof getCategoryById>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategoryById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCategoryById>>,
          TError,
          Awaited<ReturnType<typeof getCategoryById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCategoryById<TData = Awaited<ReturnType<typeof getCategoryById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategoryById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCategoryById>>,
          TError,
          Awaited<ReturnType<typeof getCategoryById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCategoryById<TData = Awaited<ReturnType<typeof getCategoryById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategoryById>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCategoryById<TData = Awaited<ReturnType<typeof getCategoryById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategoryById>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCategoryByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export const updateCategory = (
    id: number,
    updateCategoryRequest: UpdateCategoryRequest,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/categories/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateCategoryRequest, signal
    },
      options);
    }
  


export const getUpdateCategoryMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCategory>>, TError,{id: number;data: UpdateCategoryRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
): UseMutationOptions<Awaited<ReturnType<typeof updateCategory>>, TError,{id: number;data: UpdateCategoryRequest}, TContext> => {

const mutationKey = ['updateCategory'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCategory>>, {id: number;data: UpdateCategoryRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateCategory(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof updateCategory>>>
    export type UpdateCategoryMutationBody = UpdateCategoryRequest
    export type UpdateCategoryMutationError = unknown

    export const useUpdateCategory = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCategory>>, TError,{id: number;data: UpdateCategoryRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCategory>>,
        TError,
        {id: number;data: UpdateCategoryRequest},
        TContext
      > => {
      return useMutation(getUpdateCategoryMutationOptions(options), queryClient);
    }
    
export const deleteCategory = (
    id: number,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/categories/${id}`, method: 'DELETE', signal
    },
      options);
    }
  


export const getDeleteCategoryMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCategory>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCategory>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteCategory'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCategory>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteCategory(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCategory>>>
    
    export type DeleteCategoryMutationError = unknown

    export const useDeleteCategory = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCategory>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCategory>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteCategoryMutationOptions(options), queryClient);
    }
    
export const getDepartments = (
    params?: GetDepartmentsParams,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/departments`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetDepartmentsQueryKey = (params?: GetDepartmentsParams,) => {
    return [
    `/api/departments`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetDepartmentsQueryOptions = <TData = Awaited<ReturnType<typeof getDepartments>>, TError = unknown>(params?: GetDepartmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepartments>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDepartmentsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDepartments>>> = ({ signal }) => getDepartments(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDepartments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDepartmentsQueryResult = NonNullable<Awaited<ReturnType<typeof getDepartments>>>
export type GetDepartmentsQueryError = unknown


export function useGetDepartments<TData = Awaited<ReturnType<typeof getDepartments>>, TError = unknown>(
 params: undefined |  GetDepartmentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepartments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDepartments>>,
          TError,
          Awaited<ReturnType<typeof getDepartments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDepartments<TData = Awaited<ReturnType<typeof getDepartments>>, TError = unknown>(
 params?: GetDepartmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepartments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDepartments>>,
          TError,
          Awaited<ReturnType<typeof getDepartments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDepartments<TData = Awaited<ReturnType<typeof getDepartments>>, TError = unknown>(
 params?: GetDepartmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepartments>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetDepartments<TData = Awaited<ReturnType<typeof getDepartments>>, TError = unknown>(
 params?: GetDepartmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepartments>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDepartmentsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export const createDepartment = (
    createDepartmentRequest: CreateDepartmentRequest,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/departments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createDepartmentRequest, signal
    },
      options);
    }
  


export const getCreateDepartmentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDepartment>>, TError,{data: CreateDepartmentRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
): UseMutationOptions<Awaited<ReturnType<typeof createDepartment>>, TError,{data: CreateDepartmentRequest}, TContext> => {

const mutationKey = ['createDepartment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDepartment>>, {data: CreateDepartmentRequest}> = (props) => {
          const {data} = props ?? {};

          return  createDepartment(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateDepartmentMutationResult = NonNullable<Awaited<ReturnType<typeof createDepartment>>>
    export type CreateDepartmentMutationBody = CreateDepartmentRequest
    export type CreateDepartmentMutationError = unknown

    export const useCreateDepartment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDepartment>>, TError,{data: CreateDepartmentRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createDepartment>>,
        TError,
        {data: CreateDepartmentRequest},
        TContext
      > => {
      return useMutation(getCreateDepartmentMutationOptions(options), queryClient);
    }
    
export const getDepartmentById = (
    id: number,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/departments/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetDepartmentByIdQueryKey = (id: number,) => {
    return [
    `/api/departments/${id}`
    ] as const;
    }

    
export const getGetDepartmentByIdQueryOptions = <TData = Awaited<ReturnType<typeof getDepartmentById>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepartmentById>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDepartmentByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDepartmentById>>> = ({ signal }) => getDepartmentById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDepartmentById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDepartmentByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getDepartmentById>>>
export type GetDepartmentByIdQueryError = unknown


export function useGetDepartmentById<TData = Awaited<ReturnType<typeof getDepartmentById>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepartmentById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDepartmentById>>,
          TError,
          Awaited<ReturnType<typeof getDepartmentById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDepartmentById<TData = Awaited<ReturnType<typeof getDepartmentById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepartmentById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDepartmentById>>,
          TError,
          Awaited<ReturnType<typeof getDepartmentById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDepartmentById<TData = Awaited<ReturnType<typeof getDepartmentById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepartmentById>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetDepartmentById<TData = Awaited<ReturnType<typeof getDepartmentById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepartmentById>>, TError, TData>>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDepartmentByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export const updateDepartment = (
    id: number,
    updateDepartmentRequest: UpdateDepartmentRequest,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/departments/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateDepartmentRequest, signal
    },
      options);
    }
  


export const getUpdateDepartmentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDepartment>>, TError,{id: number;data: UpdateDepartmentRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
): UseMutationOptions<Awaited<ReturnType<typeof updateDepartment>>, TError,{id: number;data: UpdateDepartmentRequest}, TContext> => {

const mutationKey = ['updateDepartment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateDepartment>>, {id: number;data: UpdateDepartmentRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateDepartment(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateDepartmentMutationResult = NonNullable<Awaited<ReturnType<typeof updateDepartment>>>
    export type UpdateDepartmentMutationBody = UpdateDepartmentRequest
    export type UpdateDepartmentMutationError = unknown

    export const useUpdateDepartment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDepartment>>, TError,{id: number;data: UpdateDepartmentRequest}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateDepartment>>,
        TError,
        {id: number;data: UpdateDepartmentRequest},
        TContext
      > => {
      return useMutation(getUpdateDepartmentMutationOptions(options), queryClient);
    }
    
export const deleteDepartment = (
    id: number,
 options?: SecondParameter<typeof apiOrvalClient>,signal?: AbortSignal
) => {
      
      
      return apiOrvalClient<Result>(
      {url: `/api/departments/${id}`, method: 'DELETE', signal
    },
      options);
    }
  


export const getDeleteDepartmentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDepartment>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDepartment>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteDepartment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDepartment>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteDepartment(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteDepartmentMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDepartment>>>
    
    export type DeleteDepartmentMutationError = unknown

    export const useDeleteDepartment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDepartment>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiOrvalClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDepartment>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteDepartmentMutationOptions(options), queryClient);
    }
