/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

export const GetAttendanceQueryParams = zod.object({
  "year": zod.number().optional(),
  "month": zod.number().optional(),
  "departmentId": zod.number().optional()
})

export const GetAttendanceResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const SetAttendanceCellBody = zod.object({
  "employeeId": zod.uuid().optional(),
  "date": zod.iso.date().optional(),
  "leaveReasonId": zod.number().optional(),
  "note": zod.string().nullish()
})

export const SetAttendanceCellResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const BulkSetAttendanceBody = zod.object({
  "items": zod.array(zod.object({
  "employeeId": zod.uuid().optional(),
  "date": zod.iso.date().optional(),
  "leaveReasonId": zod.number().optional(),
  "note": zod.string().nullish()
})).optional()
})

export const BulkSetAttendanceResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetAttendanceHistoryParams = zod.object({
  "employeeId": zod.uuid()
})

export const GetAttendanceHistoryQueryParams = zod.object({
  "year": zod.number().optional(),
  "month": zod.number().optional()
})

export const GetAttendanceHistoryResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const ExportAttendancesQueryParams = zod.object({
  "year": zod.number().optional(),
  "month": zod.number().optional(),
  "departmentId": zod.number().optional()
})


export const LoginUserBody = zod.object({
  "username": zod.string().optional(),
  "password": zod.string().optional()
})

export const LoginUserResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const RefreshUserResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const LogoutUserResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const AuthChangePasswordBody = zod.object({
  "oldPassword": zod.string().optional(),
  "newPassword": zod.string().optional()
})

export const AuthChangePasswordResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetCategoriesQueryParams = zod.object({
  "type": zod.string().optional()
})

export const GetCategoriesResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const CreateCategoryBody = zod.object({
  "type": zod.string().optional(),
  "code": zod.string().optional(),
  "name": zod.string().optional(),
  "displayOrder": zod.number().optional()
})

export const CreateCategoryResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetCategoryByIdParams = zod.object({
  "id": zod.number()
})

export const GetCategoryByIdResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const UpdateCategoryParams = zod.object({
  "id": zod.number()
})

export const UpdateCategoryBody = zod.object({
  "type": zod.string().nullish(),
  "code": zod.string().nullish(),
  "name": zod.string().nullish(),
  "displayOrder": zod.number().optional()
})

export const UpdateCategoryResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const DeleteCategoryParams = zod.object({
  "id": zod.number()
})

export const DeleteCategoryResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const bulkDeleteCategorysBodyRegExpOne = new RegExp('^-?(?:0|[1-9]\\d\*)$');
export const bulkDeleteCategorysBodyRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)$');


export const BulkDeleteCategorysBodyItem = zod.union([zod.number().stringFormat('int32', bulkDeleteCategorysBodyRegExpOne),zod.stringFormat('int32', bulkDeleteCategorysBodyRegExpTwo)])
export const BulkDeleteCategorysBody = zod.array(BulkDeleteCategorysBodyItem)

export const BulkDeleteCategorysResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetDashboardResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetDayOffsResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const CreateDayOffBody = zod.object({
  "name": zod.string().optional(),
  "symbol": zod.string().nullish(),
  "color": zod.string().nullish(),
  "recurringType": zod.number().optional(),
  "date": zod.iso.date().nullish(),
  "yearlyMonth": zod.number().optional(),
  "yearlyDay": zod.number().optional(),
  "weekDay": zod.number().optional(),
  "isActive": zod.boolean().optional(),
  "displayOrder": zod.number().optional()
})

export const CreateDayOffResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetDayOffByIdParams = zod.object({
  "id": zod.number()
})

export const GetDayOffByIdResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const UpdateDayOffParams = zod.object({
  "id": zod.number()
})

export const UpdateDayOffBody = zod.object({
  "name": zod.string().nullish(),
  "symbol": zod.string().nullish(),
  "color": zod.string().nullish(),
  "recurringType": zod.union([zod.null(),zod.number()]).optional(),
  "date": zod.iso.date().nullish(),
  "yearlyMonth": zod.number().optional(),
  "yearlyDay": zod.number().optional(),
  "weekDay": zod.number().optional(),
  "isActive": zod.boolean().nullish(),
  "displayOrder": zod.number().optional()
})

export const UpdateDayOffResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const DeleteDayOffParams = zod.object({
  "id": zod.number()
})

export const DeleteDayOffResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetDepartmentsQueryParams = zod.object({
  "activeOnly": zod.boolean().optional()
})

export const GetDepartmentsResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const CreateDepartmentBody = zod.object({
  "code": zod.string().optional(),
  "name": zod.string().optional(),
  "shortName": zod.string().nullish(),
  "leaderName": zod.string().nullish(),
  "phoneNumber": zod.string().nullish(),
  "displayOrder": zod.number().optional()
})

export const CreateDepartmentResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetDepartmentByIdParams = zod.object({
  "id": zod.number()
})

export const GetDepartmentByIdResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const UpdateDepartmentParams = zod.object({
  "id": zod.number()
})

export const UpdateDepartmentBody = zod.object({
  "code": zod.string().nullish(),
  "name": zod.string().nullish(),
  "shortName": zod.string().nullish(),
  "leaderName": zod.string().nullish(),
  "phoneNumber": zod.string().nullish(),
  "displayOrder": zod.number().optional(),
  "isActive": zod.boolean().nullish()
})

export const UpdateDepartmentResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const DeleteDepartmentParams = zod.object({
  "id": zod.number()
})

export const DeleteDepartmentResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const bulkDeleteDepartmentsBodyRegExpOne = new RegExp('^-?(?:0|[1-9]\\d\*)$');
export const bulkDeleteDepartmentsBodyRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)$');


export const BulkDeleteDepartmentsBodyItem = zod.union([zod.number().stringFormat('int32', bulkDeleteDepartmentsBodyRegExpOne),zod.stringFormat('int32', bulkDeleteDepartmentsBodyRegExpTwo)])
export const BulkDeleteDepartmentsBody = zod.array(BulkDeleteDepartmentsBodyItem)

export const BulkDeleteDepartmentsResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetDocSourcesResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const CreateDocSourceBody = zod.object({
  "code": zod.string().optional(),
  "name": zod.string().optional(),
  "level": zod.string().optional(),
  "displayOrder": zod.number().optional()
})

export const CreateDocSourceResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetDocSourceByIdParams = zod.object({
  "id": zod.number()
})

export const GetDocSourceByIdResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const UpdateDocSourceParams = zod.object({
  "id": zod.number()
})

export const UpdateDocSourceBody = zod.object({
  "code": zod.string().nullish(),
  "name": zod.string().nullish(),
  "level": zod.string().nullish(),
  "displayOrder": zod.number().optional()
})

export const UpdateDocSourceResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const DeleteDocSourceParams = zod.object({
  "id": zod.number()
})

export const DeleteDocSourceResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const bulkDeleteDocSourcesBodyRegExpOne = new RegExp('^-?(?:0|[1-9]\\d\*)$');
export const bulkDeleteDocSourcesBodyRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)$');


export const BulkDeleteDocSourcesBodyItem = zod.union([zod.number().stringFormat('int32', bulkDeleteDocSourcesBodyRegExpOne),zod.stringFormat('int32', bulkDeleteDocSourcesBodyRegExpTwo)])
export const BulkDeleteDocSourcesBody = zod.array(BulkDeleteDocSourcesBodyItem)

export const BulkDeleteDocSourcesResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetDocumentsQueryParams = zod.object({
  "Keyword": zod.string().optional(),
  "SourceId": zod.number().optional(),
  "Page": zod.number().optional(),
  "PageSize": zod.number().optional(),
  "SortBy": zod.string().optional(),
  "IsDescending": zod.boolean().optional(),
  "Query": zod.string().optional(),
  "Skip": zod.number().optional(),
  "Take": zod.number().optional()
})

export const GetDocumentsResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const CreateDocumentBody = zod.object({
  "docNumber": zod.string().optional(),
  "title": zod.string().optional(),
  "sourceId": zod.number().optional(),
  "docTypeId": zod.number().optional(),
  "issueDate": zod.iso.date().nullish(),
  "signer": zod.string().nullish(),
  "filePath": zod.string().nullish(),
  "createdBy": zod.string().nullish()
})

export const CreateDocumentResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetDocumentByIdParams = zod.object({
  "id": zod.uuid()
})

export const GetDocumentByIdResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const UpdateDocumentParams = zod.object({
  "id": zod.uuid()
})

export const UpdateDocumentBody = zod.object({
  "docNumber": zod.string().nullish(),
  "title": zod.string().nullish(),
  "sourceId": zod.number().optional(),
  "docTypeId": zod.number().optional(),
  "issueDate": zod.iso.date().nullish(),
  "signer": zod.string().nullish(),
  "filePath": zod.string().nullish()
})

export const UpdateDocumentResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const DeleteDocumentParams = zod.object({
  "id": zod.uuid()
})

export const DeleteDocumentResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const BulkDeleteDocumentsBodyItem = zod.uuid()
export const BulkDeleteDocumentsBody = zod.array(BulkDeleteDocumentsBodyItem)

export const BulkDeleteDocumentsResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetEmployeesQueryParams = zod.object({
  "departmentId": zod.number().optional(),
  "activeOnly": zod.boolean().optional(),
  "keyword": zod.string().optional()
})

export const GetEmployeesResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const createEmployeeBodyBaseSalaryRegExpOne = new RegExp('^-?(?:0|[1-9]\\d\*)(?:\\.\\d+)?$');
export const createEmployeeBodyBaseSalaryRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)(?:\\.\\d+)?$');
export const createEmployeeBodyAllowanceRegExpOne = new RegExp('^-?(?:0|[1-9]\\d\*)(?:\\.\\d+)?$');
export const createEmployeeBodyAllowanceRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)(?:\\.\\d+)?$');


export const CreateEmployeeBody = zod.object({
  "employeeCode": zod.string().optional(),
  "fullName": zod.string().optional(),
  "departmentId": zod.number().optional(),
  "position": zod.string().nullish(),
  "baseSalary": zod.union([zod.number().stringFormat('double', createEmployeeBodyBaseSalaryRegExpOne),zod.stringFormat('double', createEmployeeBodyBaseSalaryRegExpTwo)]).optional(),
  "allowance": zod.union([zod.number().stringFormat('double', createEmployeeBodyAllowanceRegExpOne),zod.stringFormat('double', createEmployeeBodyAllowanceRegExpTwo)]).optional(),
  "phoneNumber": zod.string().nullish(),
  "avatarUrl": zod.string().nullish(),
  "displayOrder": zod.number().optional(),
  "joinDate": zod.iso.date().nullish()
})

export const CreateEmployeeResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetEmployeeByIdParams = zod.object({
  "id": zod.uuid()
})

export const GetEmployeeByIdResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const UpdateEmployeeParams = zod.object({
  "id": zod.uuid()
})

export const updateEmployeeBodyBaseSalaryRegExpOne = new RegExp('^-?(?:0|[1-9]\\d\*)(?:\\.\\d+)?$');
export const updateEmployeeBodyBaseSalaryRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)(?:\\.\\d+)?$');
export const updateEmployeeBodyAllowanceRegExpOne = new RegExp('^-?(?:0|[1-9]\\d\*)(?:\\.\\d+)?$');
export const updateEmployeeBodyAllowanceRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)(?:\\.\\d+)?$');


export const UpdateEmployeeBody = zod.object({
  "employeeCode": zod.string().nullish(),
  "fullName": zod.string().nullish(),
  "departmentId": zod.number().optional(),
  "position": zod.string().nullish(),
  "baseSalary": zod.union([zod.number().stringFormat('double', updateEmployeeBodyBaseSalaryRegExpOne),zod.stringFormat('double', updateEmployeeBodyBaseSalaryRegExpTwo)]).nullish(),
  "allowance": zod.union([zod.number().stringFormat('double', updateEmployeeBodyAllowanceRegExpOne),zod.stringFormat('double', updateEmployeeBodyAllowanceRegExpTwo)]).nullish(),
  "phoneNumber": zod.string().nullish(),
  "avatarUrl": zod.string().nullish(),
  "isActive": zod.boolean().nullish(),
  "displayOrder": zod.number().optional(),
  "joinDate": zod.iso.date().nullish()
})

export const UpdateEmployeeResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const DeleteEmployeeParams = zod.object({
  "id": zod.uuid()
})

export const DeleteEmployeeResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const BulkDeleteEmployeesBodyItem = zod.uuid()
export const BulkDeleteEmployeesBody = zod.array(BulkDeleteEmployeesBodyItem)

export const BulkDeleteEmployeesResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetLeaveReasonsResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const createLeaveReasonBodySalaryRatioRegExpOne = new RegExp('^-?(?:0|[1-9]\\d\*)(?:\\.\\d+)?$');
export const createLeaveReasonBodySalaryRatioRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)(?:\\.\\d+)?$');


export const CreateLeaveReasonBody = zod.object({
  "code": zod.string().optional(),
  "name": zod.string().optional(),
  "symbol": zod.string().nullish(),
  "color": zod.string().nullish(),
  "isPaid": zod.boolean().optional(),
  "salaryRatio": zod.union([zod.number().stringFormat('double', createLeaveReasonBodySalaryRatioRegExpOne),zod.stringFormat('double', createLeaveReasonBodySalaryRatioRegExpTwo)]).optional(),
  "displayOrder": zod.number().optional()
})

export const CreateLeaveReasonResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetLeaveReasonByIdParams = zod.object({
  "id": zod.number()
})

export const GetLeaveReasonByIdResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const UpdateLeaveReasonParams = zod.object({
  "id": zod.number()
})

export const updateLeaveReasonBodySalaryRatioRegExpOne = new RegExp('^-?(?:0|[1-9]\\d\*)(?:\\.\\d+)?$');
export const updateLeaveReasonBodySalaryRatioRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)(?:\\.\\d+)?$');


export const UpdateLeaveReasonBody = zod.object({
  "code": zod.string().nullish(),
  "name": zod.string().nullish(),
  "symbol": zod.string().nullish(),
  "color": zod.string().nullish(),
  "isPaid": zod.boolean().nullish(),
  "salaryRatio": zod.union([zod.number().stringFormat('double', updateLeaveReasonBodySalaryRatioRegExpOne),zod.stringFormat('double', updateLeaveReasonBodySalaryRatioRegExpTwo)]).nullish(),
  "displayOrder": zod.number().optional()
})

export const UpdateLeaveReasonResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const DeleteLeaveReasonParams = zod.object({
  "id": zod.number()
})

export const DeleteLeaveReasonResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const bulkDeleteLeaveReasonsBodyRegExpOne = new RegExp('^-?(?:0|[1-9]\\d\*)$');
export const bulkDeleteLeaveReasonsBodyRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)$');


export const BulkDeleteLeaveReasonsBodyItem = zod.union([zod.number().stringFormat('int32', bulkDeleteLeaveReasonsBodyRegExpOne),zod.stringFormat('int32', bulkDeleteLeaveReasonsBodyRegExpTwo)])
export const BulkDeleteLeaveReasonsBody = zod.array(BulkDeleteLeaveReasonsBodyItem)

export const BulkDeleteLeaveReasonsResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetPositionsResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const CreatePositionBody = zod.object({
  "code": zod.string().optional(),
  "name": zod.string().optional(),
  "displayOrder": zod.number().optional(),
  "isActive": zod.boolean().optional()
})

export const CreatePositionResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetPositionByIdParams = zod.object({
  "id": zod.number()
})

export const GetPositionByIdResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const UpdatePositionParams = zod.object({
  "id": zod.number()
})

export const UpdatePositionBody = zod.object({
  "code": zod.string().nullish(),
  "name": zod.string().nullish(),
  "displayOrder": zod.number().optional(),
  "isActive": zod.boolean().nullish()
})

export const UpdatePositionResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const DeletePositionParams = zod.object({
  "id": zod.number()
})

export const DeletePositionResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const bulkDeletePositionsBodyRegExpOne = new RegExp('^-?(?:0|[1-9]\\d\*)$');
export const bulkDeletePositionsBodyRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)$');


export const BulkDeletePositionsBodyItem = zod.union([zod.number().stringFormat('int32', bulkDeletePositionsBodyRegExpOne),zod.stringFormat('int32', bulkDeletePositionsBodyRegExpTwo)])
export const BulkDeletePositionsBody = zod.array(BulkDeletePositionsBodyItem)

export const BulkDeletePositionsResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetSalaryQueryParams = zod.object({
  "Year": zod.number().optional(),
  "Month": zod.number().optional(),
  "DepartmentId": zod.number().optional()
})

export const GetSalaryResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const ExportSalaryQueryParams = zod.object({
  "Year": zod.number().optional(),
  "Month": zod.number().optional(),
  "DepartmentId": zod.number().optional()
})


export const GetTaskLogsParams = zod.object({
  "taskId": zod.uuid()
})

export const GetTaskLogsResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const CreateTaskLogParams = zod.object({
  "taskId": zod.uuid()
})

export const CreateTaskLogBody = zod.object({
  "progressNote": zod.string().optional(),
  "updatedBy": zod.string().nullish()
})

export const CreateTaskLogResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetTasksQueryParams = zod.object({
  "Keyword": zod.string().optional(),
  "DepartmentId": zod.number().optional(),
  "Status": zod.string().optional(),
  "Tab": zod.string().optional(),
  "Page": zod.number().optional(),
  "PageSize": zod.number().optional(),
  "SortBy": zod.string().optional(),
  "IsDescending": zod.boolean().optional(),
  "Query": zod.string().optional(),
  "Skip": zod.number().optional(),
  "Take": zod.number().optional()
})

export const GetTasksResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const CreateTaskBody = zod.object({
  "documentId": zod.uuid().optional(),
  "taskCode": zod.string().nullish(),
  "taskContent": zod.string().optional(),
  "mainDepartmentId": zod.number().optional(),
  "coDepartmentIds": zod.string().nullish(),
  "assigneeName": zod.string().nullish(),
  "dueDate": zod.iso.datetime({}).nullish(),
  "initialNote": zod.string().nullish(),
  "createdBy": zod.string().nullish()
})

export const CreateTaskResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetTaskByIdParams = zod.object({
  "id": zod.uuid()
})

export const GetTaskByIdResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const UpdateTaskParams = zod.object({
  "id": zod.uuid()
})

export const UpdateTaskBody = zod.object({
  "taskContent": zod.string().nullish(),
  "mainDepartmentId": zod.number().optional(),
  "coDepartmentIds": zod.string().nullish(),
  "assigneeName": zod.string().nullish(),
  "dueDate": zod.iso.datetime({}).nullish(),
  "status": zod.string().nullish(),
  "completedDate": zod.iso.date().nullish(),
  "latestResult": zod.string().nullish()
})

export const UpdateTaskResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const DeleteTaskParams = zod.object({
  "id": zod.uuid()
})

export const DeleteTaskResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const CompleteTaskByIdParams = zod.object({
  "id": zod.uuid()
})

export const CompleteTaskByIdBody = zod.object({
  "latestResult": zod.string().nullish(),
  "completedDate": zod.iso.date().nullish()
})

export const CompleteTaskByIdResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const BulkDeleteTasksBodyItem = zod.uuid()
export const BulkDeleteTasksBody = zod.array(BulkDeleteTasksBodyItem)

export const BulkDeleteTasksResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const ExportTasksQueryParams = zod.object({
  "DepartmentId": zod.number().optional(),
  "Tab": zod.string().optional(),
  "Keyword": zod.string().optional()
})
