/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

export const LoginUserBody = zod.object({
  "username": zod.string().optional(),
  "password": zod.string().optional()
})

export const LoginUserResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const RefreshUserResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const LogoutUserResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const AuthChangePasswordBody = zod.object({
  "oldPassword": zod.string().optional(),
  "newPassword": zod.string().optional()
})

export const AuthChangePasswordResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetDocumentsQueryParams = zod.object({
  "Keyword": zod.string().optional(),
  "SourceId": zod.number().optional(),
  "Page": zod.number().optional(),
  "PageSize": zod.number().optional(),
  "SortBy": zod.string().optional(),
  "IsDescending": zod.boolean().optional(),
  "Query": zod.string().optional(),
  "Skip": zod.number().optional(),
  "Take": zod.number().optional()
})

export const GetDocumentsResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const CreateDocumentBody = zod.object({
  "docNumber": zod.string().optional(),
  "title": zod.string().optional(),
  "sourceId": zod.number().optional(),
  "docTypeId": zod.number().optional(),
  "issueDate": zod.iso.date().nullish(),
  "signer": zod.string().nullish(),
  "filePath": zod.string().nullish(),
  "createdBy": zod.string().nullish()
})

export const CreateDocumentResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetDocumentByIdParams = zod.object({
  "id": zod.uuid()
})

export const GetDocumentByIdResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const UpdateDocumentParams = zod.object({
  "id": zod.uuid()
})

export const UpdateDocumentBody = zod.object({
  "docNumber": zod.string().nullish(),
  "title": zod.string().nullish(),
  "sourceId": zod.number().optional(),
  "docTypeId": zod.number().optional(),
  "issueDate": zod.iso.date().nullish(),
  "signer": zod.string().nullish(),
  "filePath": zod.string().nullish()
})

export const UpdateDocumentResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const DeleteDocumentParams = zod.object({
  "id": zod.uuid()
})

export const DeleteDocumentResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetTasksQueryParams = zod.object({
  "Keyword": zod.string().optional(),
  "DepartmentId": zod.number().optional(),
  "Status": zod.string().optional(),
  "Tab": zod.string().optional(),
  "Page": zod.number().optional(),
  "PageSize": zod.number().optional(),
  "SortBy": zod.string().optional(),
  "IsDescending": zod.boolean().optional(),
  "Query": zod.string().optional(),
  "Skip": zod.number().optional(),
  "Take": zod.number().optional()
})

export const GetTasksResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const CreateTaskBody = zod.object({
  "documentId": zod.uuid().optional(),
  "taskContent": zod.string().optional(),
  "mainDepartmentId": zod.number().optional(),
  "coDepartmentIds": zod.string().nullish(),
  "assigneeName": zod.string().nullish(),
  "dueDate": zod.iso.date().nullish(),
  "initialNote": zod.string().nullish(),
  "createdBy": zod.string().nullish()
})

export const CreateTaskResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetTaskByIdParams = zod.object({
  "id": zod.uuid()
})

export const GetTaskByIdResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const UpdateTaskParams = zod.object({
  "id": zod.uuid()
})

export const UpdateTaskBody = zod.object({
  "taskContent": zod.string().nullish(),
  "mainDepartmentId": zod.number().optional(),
  "coDepartmentIds": zod.string().nullish(),
  "assigneeName": zod.string().nullish(),
  "dueDate": zod.iso.date().nullish(),
  "status": zod.string().nullish(),
  "completedDate": zod.iso.date().nullish(),
  "latestResult": zod.string().nullish()
})

export const UpdateTaskResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const DeleteTaskParams = zod.object({
  "id": zod.uuid()
})

export const DeleteTaskResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const CompleteTaskByIdParams = zod.object({
  "id": zod.uuid()
})

export const CompleteTaskByIdBody = zod.object({
  "latestResult": zod.string().nullish(),
  "completedDate": zod.iso.date().nullish()
})

export const CompleteTaskByIdResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const ExportTasksQueryParams = zod.object({
  "DepartmentId": zod.number().optional(),
  "Tab": zod.string().optional(),
  "Keyword": zod.string().optional()
})

export const ExportTasksResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetTaskLogsParams = zod.object({
  "taskId": zod.uuid()
})

export const GetTaskLogsResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const CreateTaskLogParams = zod.object({
  "taskId": zod.uuid()
})

export const CreateTaskLogBody = zod.object({
  "progressNote": zod.string().optional(),
  "updatedBy": zod.string().nullish()
})

export const CreateTaskLogResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetDashboardResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetDocSourcesResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const CreateDocSourceBody = zod.object({
  "code": zod.string().optional(),
  "name": zod.string().optional(),
  "level": zod.string().optional(),
  "displayOrder": zod.number().optional()
})

export const CreateDocSourceResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetDocSourceByIdParams = zod.object({
  "id": zod.number()
})

export const GetDocSourceByIdResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const UpdateDocSourceParams = zod.object({
  "id": zod.number()
})

export const UpdateDocSourceBody = zod.object({
  "code": zod.string().nullish(),
  "name": zod.string().nullish(),
  "level": zod.string().nullish(),
  "displayOrder": zod.number().optional()
})

export const UpdateDocSourceResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const DeleteDocSourceParams = zod.object({
  "id": zod.number()
})

export const DeleteDocSourceResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetCategoriesQueryParams = zod.object({
  "type": zod.string().optional()
})

export const GetCategoriesResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const CreateCategoryBody = zod.object({
  "type": zod.string().optional(),
  "code": zod.string().optional(),
  "name": zod.string().optional(),
  "displayOrder": zod.number().optional()
})

export const CreateCategoryResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetCategoryByIdParams = zod.object({
  "id": zod.number()
})

export const GetCategoryByIdResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const UpdateCategoryParams = zod.object({
  "id": zod.number()
})

export const UpdateCategoryBody = zod.object({
  "type": zod.string().nullish(),
  "code": zod.string().nullish(),
  "name": zod.string().nullish(),
  "displayOrder": zod.number().optional()
})

export const UpdateCategoryResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const DeleteCategoryParams = zod.object({
  "id": zod.number()
})

export const DeleteCategoryResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetDepartmentsQueryParams = zod.object({
  "activeOnly": zod.boolean().optional()
})

export const GetDepartmentsResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const CreateDepartmentBody = zod.object({
  "code": zod.string().optional(),
  "name": zod.string().optional(),
  "shortName": zod.string().nullish(),
  "leaderName": zod.string().nullish(),
  "phoneNumber": zod.string().nullish(),
  "displayOrder": zod.number().optional()
})

export const CreateDepartmentResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const GetDepartmentByIdParams = zod.object({
  "id": zod.number()
})

export const GetDepartmentByIdResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const UpdateDepartmentParams = zod.object({
  "id": zod.number()
})

export const UpdateDepartmentBody = zod.object({
  "code": zod.string().nullish(),
  "name": zod.string().nullish(),
  "shortName": zod.string().nullish(),
  "leaderName": zod.string().nullish(),
  "phoneNumber": zod.string().nullish(),
  "displayOrder": zod.number().optional(),
  "isActive": zod.boolean().nullish()
})

export const UpdateDepartmentResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})


export const DeleteDepartmentParams = zod.object({
  "id": zod.number()
})

export const DeleteDepartmentResponse = zod.object({
  "isError": zod.boolean().optional(),
  "data": zod.unknown().optional(),
  "statusCode": zod.number().optional(),
  "errorMessage": zod.string().nullish()
})
