/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ChangePasswordRequest {
  oldPassword?: string;
  newPassword?: string;
}
