/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface CreateDepartmentRequest {
  code?: string;
  name?: string;
  /** @nullable */
  shortName?: string | null;
  /** @nullable */
  leaderName?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  displayOrder?: number;
}
