/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface CreateLeaveReasonRequest {
  code?: string;
  name?: string;
  /** @nullable */
  symbol?: string | null;
  /** @nullable */
  color?: string | null;
  isPaid?: boolean;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  salaryRatio?: number | string;
  displayOrder?: number;
}
