/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface CreateEmploymentHistoryRequest {
  employeeId?: string;
  departmentId?: number;
  positionId?: number;
  /** @nullable */
  contractId?: string | null;
  effectiveFrom?: string;
  /** @nullable */
  effectiveTo?: string | null;
  /** @nullable */
  reason?: string | null;
}
