/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { DayOffRecurringType } from './dayOffRecurringType';

export interface CreateDayOffRequest {
  name?: string;
  /** @nullable */
  symbol?: string | null;
  /** @nullable */
  color?: string | null;
  recurringType?: DayOffRecurringType;
  /** @nullable */
  date?: string | null;
  yearlyMonth?: number;
  yearlyDay?: number;
  weekDay?: number;
  isActive?: boolean;
  displayOrder?: number;
}
