/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface CreateTaskRequest {
  documentId?: string;
  taskContent?: string;
  mainDepartmentId?: number;
  /** @nullable */
  coDepartmentIds?: string | null;
  /** @nullable */
  assigneeName?: string | null;
  /** @nullable */
  dueDate?: string | null;
  /** @nullable */
  initialNote?: string | null;
  /** @nullable */
  createdBy?: string | null;
}
