/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface CreateSalaryHistoryRequest {
  employeeId?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  salaryCoefficient?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  allowance?: number | string;
  effectiveFrom?: string;
  /** @nullable */
  effectiveTo?: string | null;
  /** @nullable */
  reason?: string | null;
}
