/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface CreateEmployeeRequest {
  employeeCode?: string;
  fullName?: string;
  departmentId?: number;
  /** @nullable */
  position?: string | null;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  baseSalary?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  allowance?: number | string;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
  displayOrder?: number;
  /** @nullable */
  joinDate?: string | null;
}
