/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface CreateDocumentRequest {
  docNumber?: string;
  title?: string;
  sourceId?: number;
  docTypeId?: number;
  /** @nullable */
  issueDate?: string | null;
  /** @nullable */
  signer?: string | null;
  /** @nullable */
  filePath?: string | null;
  /** @nullable */
  createdBy?: string | null;
}
