/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export type GetApiDocumentsParams = {
Keyword?: string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
SourceId?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
Page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
PageSize?: number | string;
SortBy?: string;
IsDescending?: boolean;
Query?: string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
Skip?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
Take?: number | string;
};
