/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TaskTab } from './taskTab';

export type GetExportTasksParams = {
DepartmentId?: number;
Tab?: TaskTab;
Keyword?: string;
};
