/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TaskStatus } from './taskStatus';
import type { TaskTab } from './taskTab';

export type GetTasksParams = {
Keyword?: string;
DepartmentId?: number;
Status?: TaskStatus;
Tab?: TaskTab;
Page?: number;
PageSize?: number;
SortBy?: string;
IsDescending?: boolean;
Query?: string;
Skip?: number;
Take?: number;
};
