/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export type GetTasksParams = {
Keyword?: string;
DepartmentId?: number;
Status?: string;
Tab?: string;
Page?: number;
PageSize?: number;
SortBy?: string;
IsDescending?: boolean;
Query?: string;
Skip?: number;
Take?: number;
};
