/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export * from './changePasswordRequest';
export * from './completeTaskRequest';
export * from './createCategoryRequest';
export * from './createDepartmentRequest';
export * from './createDocSourceRequest';
export * from './createDocumentRequest';
export * from './createTaskLogRequest';
export * from './createTaskRequest';
export * from './exportTasksParams';
export * from './getCategoriesParams';
export * from './getDepartmentsParams';
export * from './getDocumentsParams';
export * from './getTasksParams';
export * from './loginRequest';
export * from './result';
export * from './updateCategoryRequest';
export * from './updateDepartmentRequest';
export * from './updateDocSourceRequest';
export * from './updateDocumentRequest';
export * from './updateTaskRequest';