/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateSalaryHistoryRequest {
  /**
   * @nullable
   * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
   */
  salaryCoefficient?: number | string | null;
  /**
   * @nullable
   * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
   */
  allowance?: number | string | null;
  /** @nullable */
  effectiveFrom?: string | null;
  /** @nullable */
  effectiveTo?: string | null;
  /** @nullable */
  reason?: string | null;
}
