/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateBaseSalaryRequest {
  /**
   * @minimum 1
   * @maximum 100000000
   * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
   */
  amount: number | string;
  /**
   * @minimum 2000
   * @maximum 2100
   */
  effectiveFromYear: number;
  /**
   * @minimum 1
   * @maximum 12
   */
  effectiveFromMonth: number;
  /**
   * @maxLength 255
   * @nullable
   */
  note?: string | null;
  displayOrder?: number;
}
