/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateEmployeeRequest {
  /** @nullable */
  employeeCode?: string | null;
  /** @nullable */
  fullName?: string | null;
  departmentId?: number;
  /** @nullable */
  position?: string | null;
  /**
   * @nullable
   * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
   */
  baseSalary?: number | string | null;
  /**
   * @nullable
   * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
   */
  allowance?: number | string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
  /** @nullable */
  isActive?: boolean | null;
  displayOrder?: number;
  /** @nullable */
  joinDate?: string | null;
}
