/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateLeaveReasonRequest {
  /** @nullable */
  code?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  symbol?: string | null;
  /** @nullable */
  color?: string | null;
  /** @nullable */
  isPaid?: boolean | null;
  /**
   * @nullable
   * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
   */
  salaryRatio?: number | string | null;
  displayOrder?: number;
}
