/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { DocSourceLevel } from './docSourceLevel';

export interface UpdateDocSourceRequest {
  /** @nullable */
  code?: string | null;
  /** @nullable */
  name?: string | null;
  level?: null | DocSourceLevel;
  displayOrder?: number;
}
