/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { DayOffRecurringType } from './dayOffRecurringType';

export interface UpdateDayOffRequest {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  symbol?: string | null;
  /** @nullable */
  color?: string | null;
  recurringType?: null | DayOffRecurringType;
  /** @nullable */
  date?: string | null;
  yearlyMonth?: number;
  yearlyDay?: number;
  weekDay?: number;
  /** @nullable */
  isActive?: boolean | null;
  displayOrder?: number;
}
