/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TaskStatus } from './taskStatus';

export interface UpdateTaskRequest {
  /** @nullable */
  taskContent?: string | null;
  mainDepartmentId?: number;
  /** @nullable */
  coDepartmentIds?: string | null;
  /** @nullable */
  assigneeName?: string | null;
  /** @nullable */
  dueDate?: string | null;
  status?: null | TaskStatus;
  /** @nullable */
  completedDate?: string | null;
  /** @nullable */
  latestResult?: string | null;
}
