/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryType } from './categoryType';

export interface UpdateCategoryRequest {
  type?: null | CategoryType;
  /** @nullable */
  code?: string | null;
  /** @nullable */
  name?: string | null;
  displayOrder?: number;
}
