/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * ScheduleManagement.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateCategoryRequest {
  /** @nullable */
  type?: number | null;
  /** @nullable */
  code?: string | null;
  /** @nullable */
  name?: string | null;
  displayOrder?: number;
}
